### ISSUE TITLE
NFTBounceable Standard Extension

### ISSUE THREAD

**Issue by tolya-yanot** [ton-blockchain/TIPs#67]
> ⚠️ WARNING: Standards are now published and discussed in the [TEPs](https://github.com/ton-blockchain/TEPs) repository. This page may be out of date.

# NFTBounceable

## Summary

Optional extension for [NFT Standard](https://github.com/ton-blockchain/TIPs/issues/62).

Standardizes the way NFT transfers are rolled back if the recipient has rejected the notification message.

For example, if the NFT was sent to the wrong address and the recipient smart contract does not know how to interact with the NFT

## Specification

If NFT item smart contract receive `ownership_assigned` message with `bounced` flag set it should revert ownership change and set `prev_owner` as current owner.

If NFT item smart contract receive `editorship_assigned` message with `bounced` flag set it should revert editorship change and set `prev_editor` as current editor.

**Comment by tvorogme** [comment]
It'll be perfect to add `slice get_prev_owner()  method_id {` method, so third-party software can display previous owner while NFT in sell contract / marketplace.

**Comment by EmelyanenkoK** [comment]
Looks like it should be solved on sell contract side. Indeed the chain of transfers may be arbitrary long: for instance user sends NFT to marketplace contract, marketplace deploy desired auction and send NFT there. In this case prev owner will not show _practical_ previous owner. Besides when NFT will be sent to buyer prev_owner still will be presented for no reason.

Probably something like TemporaryNFTOwner standard (or at least template) which expose `slice effective_owner() method_id {}` will match here

**Comment by tvorogme** [comment]
I thought about this question a little more.

It seems to me that it is better not to make a TemporaryNFTOwner because the scheme turns out to be too confusing.

It is much easier to make system operations on the NFT that will save prev_owner.

We can separate the operations of marketplaces / sell contracts and user operations. 

What do you think?


Also bounce from sell contract to marketplace could be implemented by marketplace.

**Comment by tvorogme** [comment]
> It is much easier to make system operations on the NFT that will save prev_owner.

> We can separate the operations of marketplaces / sell contracts and user operations.

Long chains of transactions in this case will be even easier to organize

In system transactions, we can pass `prev_owner` inside [payload](https://github.com/ton-blockchain/token-contract/blob/5bddacbb76b6ae02b78c1efb9312335d7903999e/nft/nft-item.fc#L69), so that when the sale contract is canceled, the NFT will go directly to the previous owner: [here](https://github.com/ton-blockchain/token-contract/blob/5bddacbb76b6ae02b78c1efb9312335d7903999e/nft/nft-sale.fc#L109)

**Comment by tolya-yanot** [comment]
Further discussion in TEPs
