### ISSUE TITLE
Callback standard

### ISSUE THREAD

**Issue by pyAndr3w** [ton-blockchain/TIPs#80]
## Summary
I propose to make a special op-code to call the get-method using internal message.

## Motivation
There are cases where a contract needs to get information from the get-method of another contract. Currently it can be done only through a special off-chain oracle.

## Specification
To prepare incoming data and send a response will need a special function for each get-method.

TL-B schema:

```
nothing$0 {X:Type} = Maybe X;
just$1 {X:Type} value:X = Maybe X;
left$0 {X:Type} {Y:Type} value:X = Either X Y;
right$1 {X:Type} {Y:Type} value:Y = Either X Y;


callback_request query_id:uint64 method_id:uint16
                 payload:(Maybe (Either Cell ^Cell))
                 = InternalMsgBody;

callback_response query_id:uint64
                  payload:(Either Cell ^Cell)
                  = InternalMsgBody;
```

`crc32('callback_request query_id:uint64 method_id:uint16 payload:Maybe Either Cell ^Cell = InternalMsgBody') = 0x21d60a73 & 0x7fffffff = 0x21d60a73`

`crc32('callback_response query_id:uint64 payload:Either Cell ^Cell = InternalMsgBody') = 0x68f45d36 | 0x80000000 = 0xe8f45d36`

**Comment by EmelyanenkoK** [comment]
From the TVM point of view get-method is just internal function of contract (with id defined by crc32 rule). So it doesn't seem a good idea to allow one contract to initiate methods of another without control of later. Besides, proposal lacks of serialization/de-serialization specs for stack objects.
Instead of special TVM behavior, I believe, the proper internal handlers should be used.
In ES' solidity there is `responsible view` modifier which allows by one description to generate both usual get-method and internal message handler with clear interface. We are looking at the possibility of implementing this idea in our future more secure language for TON smart contracts. The only concern is how to give the developer a clear understanding that the data obtained from this method are volatile and unreliable, since they can change even before the calling contract has received message.
